[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
build_unflags =
  -DARDUINO_USB_MODE=1
build_flags =
  -DARDUINO_USB_MODE=0
  -DREDBUTTON_VERSION=\"1.0.0\"
lib_deps = bblanchon/ArduinoJson@^7.2.1
